title: 'Invalid creadential '
description: >-
  639950890972@delivery.ph this my email on my road runner but my number is
  09295367769 but I'm trouble shoot my app but same result invalid creadential
  thank you for messege me
template:
  repo: invalid-creadential-template
  name: invalid-creadential
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
